# ETL of Pipeline 1 Data for Vizualization

## `words.csv` embeddings transformation

*Eventually want this to be an included in `pipeline_1`*

In [1]:
# Import dependencies
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
# Declare constants
PIPE_1_DATA_LOC = './data/'
VIZ_1_DATA_LOC = '../../../visualizations/part1/data/' # UGLYYYY, want to reference based on root (dev/)
# ABS_ROOT = '/Users/petergish/Desktop/working_pipeline1_data/'

# Word vectors
WORD_VECS_LOC = PIPE_1_DATA_LOC + 'embeddings/slava_words.csv'
WORDS_DISTRIB_OUTPUT_LOC = VIZ_1_DATA_LOC + 'words_sentiment_distrib.csv'
CLEAN_WORDS_OUTPUT_LOC = VIZ_1_DATA_LOC + 'cleaned_words.csv'

# Transformed tweets
TRANSFORMED_TWEETS_LOC = PIPE_1_DATA_LOC + 'transformed/slava_sentiment_transform.csv'
TWEETS_DISTRIB_OUTPUT_LOC = VIZ_1_DATA_LOC + 'slava_tweets_sentiment_distrib.csv'
CLEAN_TWEETS_OUTPUT_LOC = VIZ_1_DATA_LOC + 'cleaned_slava_tweets.csv'

# Top 10 Hashtags
HASHTAG_OUTPUT_LOC = VIZ_1_DATA_LOC + 'top_10_slava_hashtags.csv'

In [3]:
# Helper function

def formatPipelineOutput(df, drop_cols=[], col_mappings={}):
    # Drop designated columns
    clean_df = df.drop(columns=drop_cols).fillna('') # May need to do more cleaning than this...

    # Collect sentiment value counts
    summary_df = pd.DataFrame(clean_df['sentiment'].value_counts())
    
    # Format dataframe for output
    summary_df = summary_df.reset_index().rename(columns=col_mappings)

    # Build column representing each sentiment values "part of the whole"
    total_values = sum(summary_df['count'])
    summary_df['percent'] = summary_df['count'] / total_values * 100

    return clean_df, summary_df

In [4]:
# Import word vectors
words_df = pd.read_csv(WORD_VECS_LOC)
words_df.head()

,Unnamed: 0,words,vectors,cluster,cluster_value,closeness_score,sentiment_coeff,sentiment
0,0,slavaukraini,[-0.00556555 -0.03018283 -0.07193982 0.065602...,0,-1,26.910836,-26.910836,negative
1,1,ukraine,[-2.29268731e-03 -2.85607725e-02 -7.83489719e-...,0,-1,22.076856,-22.076856,negative
2,2,putin,[-0.00156193 -0.02993405 -0.07100397 0.066347...,0,-1,22.720520,-22.720520,negative
3,3,ukrainian,[-0.00668722 -0.03592093 -0.07549414 0.072225...,2,1,16.076244,16.076244,positive
4,4,russia,[-3.12011252e-04 -3.27042937e-02 -7.04228655e-...,0,-1,18.842255,-18.842255,negative

In [5]:
# Get data visualization dataframes
col_mappings = {
    'index': 'sentiment', 
    'sentiment': 'count'
}
drop_cols = ['Unnamed: 0', 'vectors', 'cluster']

clean_words_df, words_distrib_df = formatPipelineOutput(words_df, drop_cols, col_mappings)

In [6]:
# Output to visualizations/
words_distrib_df.to_csv(WORDS_DISTRIB_OUTPUT_LOC)
clean_words_df.to_csv(CLEAN_WORDS_OUTPUT_LOC)

## `slava_ukraine_sentiment_transform.csv` transformation

In [7]:
# Import transformed tweets
tweets_df = pd.read_csv(TRANSFORMED_TWEETS_LOC)
tweets_df.head()

,Unnamed: 0,date,username,retweets,tweet,hashtags,clean_tweet_words,clean_tweet,day,month,sentiment_val,sentiment
0,0,2022-02-28 23:55:31,Rob Smith 🇨🇦 🇺🇦,0,@kiraincongress Photos of rally in support of ...,NaN,"['photo', 'rally', 'support', 'ukraine', 'toro...",photo rally support ukraine toronto canada sun...,28,2,-1,negative
1,1,2022-02-28 23:55:21,Frags,0,#Russia propaganda on #Twitter attempting to d...,russia twitter ukraine,"['russia', 'propaganda', 'twitter', 'attempt',...",russia propaganda twitter attempt diminish eve...,28,2,-1,negative
2,4,2022-02-28 23:54:28,Sydfish 🇺🇦🇺🇦🇺🇦🇺🇦,0,I’ve done more than 100 in St. Petersburg. \n\...,NaN,"['do', 'st', 'petersburg', 'dm', 'would', 'lik...",do st petersburg dm would like blurb russian t...,28,2,-1,negative
3,7,2022-02-28 23:54:06,Jinx Spidox ➡️ Gdakon,0,#SlavaUkraini good night #Ukraine keep up the ...,slavaukraini ukraine,"['slavaukraini', 'good', 'night', 'ukraine', '...",slavaukraini good night ukraine keep good figh...,28,2,-1,negative
4,8,2022-02-28 23:53:58,Jackie Blue 🇺🇸 🇨🇦 🇺🇦 🌻,0,@anagin40 @NATO It sadly took Ukraine being a ...,NaN,"['sadly', 'take', 'ukraine', 'sacrificial', 'l...",sadly take ukraine sacrificial lamb world wake...,28,2,0,neutral

In [8]:
# Get data visualization dataframes
col_mappings = {
    'index': 'sentiment',
    'sentiment': 'count'
}
drop_cols = ['Unnamed: 0', 'date', 'tweet', 'retweets', 'clean_tweet_words']


clean_tweets_df, tweets_distrib_df = formatPipelineOutput(tweets_df, drop_cols, col_mappings)

In [9]:
# Output to visualizations/
tweets_distrib_df.to_csv(TWEETS_DISTRIB_OUTPUT_LOC)
clean_tweets_df.to_csv(CLEAN_TWEETS_OUTPUT_LOC)

## Top 10 Most Frequent Hashtags

In [10]:
clean_tweets_df.head(5)

,username,hashtags,clean_tweet,day,month,sentiment_val,sentiment
0,Rob Smith 🇨🇦 🇺🇦,,photo rally support ukraine toronto canada sun...,28,2,-1,negative
1,Frags,russia twitter ukraine,russia propaganda twitter attempt diminish eve...,28,2,-1,negative
2,Sydfish 🇺🇦🇺🇦🇺🇦🇺🇦,,do st petersburg dm would like blurb russian t...,28,2,-1,negative
3,Jinx Spidox ➡️ Gdakon,slavaukraini ukraine,slavaukraini good night ukraine keep good figh...,28,2,-1,negative
4,Jackie Blue 🇺🇸 🇨🇦 🇺🇦 🌻,,sadly take ukraine sacrificial lamb world wake...,28,2,0,neutral

In [11]:
filtered_hashtags = clean_tweets_df[clean_tweets_df['hashtags'] != ''][['hashtags', 'sentiment']]
filtered_hashtags.head(5)

                                      hashtags sentiment
1                 russia    twitter    ukraine  negative
3                      slavaukraini    ukraine  negative
6  ukraine    slavaukraini    ukrainerussiawar  negative
7                 slavaukraini    slavaukraine  negative
9                       slavaukraini    fckptn  negative

In [12]:
filtered_hashtags.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6682 entries, 1 to 9142
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   hashtags   6682 non-null   object
 1   sentiment  6682 non-null   object
dtypes: object(2)
memory usage: 156.6+ KB

In [13]:
split_hashtags = filtered_hashtags.set_index('sentiment') \
                                    .apply(lambda x: x.str.split('    ').explode()) \
                                    .reset_index()  
split_hashtags['hashtags'] = split_hashtags['hashtags'].replace(r'^\s*$', np.nan, regex=True).str.strip()
split_hashtags = split_hashtags.rename(columns={'hashtags': 'hashtag'}).dropna()
split_hashtags.head()

  sentiment       hashtag
0  negative        russia
1  negative       twitter
2  negative       ukraine
3  negative  slavaukraini
4  negative       ukraine

In [14]:
split_hashtags.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17646 entries, 0 to 17844
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentiment  17646 non-null  object
 1   hashtag    17646 non-null  object
dtypes: object(2)
memory usage: 413.6+ KB

In [15]:
cumulative_counts = split_hashtags['hashtag'].groupby(split_hashtags['hashtag']).count()
split_hashtags['total_count'] = split_hashtags['hashtag'].map(cumulative_counts)
split_hashtags.head()

  sentiment       hashtag  total_count
0  negative        russia          439
1  negative       twitter            3
2  negative       ukraine         1825
3  negative  slavaukraini         4325
4  negative       ukraine         1825

In [16]:
hashtag_sentiments = split_hashtags.groupby(['hashtag', 'sentiment']).value_counts().to_frame()
hashtag_sentiments = hashtag_sentiments.stack().reset_index().rename(columns={0: 'sentiment_count'}).drop(columns=['level_3'])
# grouped_hashtags = grouped_hashtags.rename(columns={0: 'count'}).sort_values('total_count', ascending=False)
# grouped_hashtags = grouped_hashtags.set_index(['hashtag', 'sentiment']).drop(columns=['level_4'])#, 'index'])
hashtag_sentiments.head()

           hashtag sentiment  total_count  sentiment_count
0         aalsmeer  positive            1                1
1      abolishnato   neutral            1                1
2       abramovich  negative            1                1
3  academicchatter  positive            1                1
4  academictwitter  positive            1                1

In [17]:
hashtag_sentiments['freq'] = ((hashtag_sentiments['sentiment_count'] / hashtag_sentiments['sentiment_count'].sum()) * 100)
hashtag_sentiments

              hashtag sentiment  total_count  sentiment_count      freq
0            aalsmeer  positive            1                1  0.005667
1         abolishnato   neutral            1                1  0.005667
2          abramovich  negative            1                1  0.005667
3     academicchatter  positive            1                1  0.005667
4     academictwitter  positive            1                1  0.005667
...               ...       ...          ...              ...       ...
2336            zhoga  negative            1                1  0.005667
2337         zhytomyr  negative            6                6  0.034002
2338        zinchenko  negative            1                1  0.005667
2339            zwift  negative            1                1  0.005667
2340        zylenskyj   neutral            1                1  0.005667

[2341 rows x 5 columns]

In [18]:
grouped_hashtags = hashtag_sentiments.set_index(['hashtag', 'sentiment']).sort_values('total_count', ascending=False)

idx_slice = [grouped_hashtags.index.get_level_values(0).unique()[i] for i in range(10)]
top_10_hashtags = grouped_hashtags.loc[idx_slice]
top_10_hashtags

                            total_count  sentiment_count       freq
hashtag          sentiment
slavaukraini     negative          4325             2195  12.439080
                 positive          4325              917   5.196645
                 neutral           4325             1213   6.874079
ukraine          neutral           1825              506   2.867505
                 negative          1825             1086   6.154369
                 positive          1825              233   1.320413
standwithukraine positive          1040              347   1.966451
                 neutral           1040              338   1.915448
                 negative          1040              355   2.011787
russia           negative           439              380   2.153463
                 positive           439               13   0.073671
                 neutral            439               46   0.260682
ukrainerussiawar positive           373               19   0.107673
                 neutral            373               89   0.504364
                 negative           373              265   1.501757
stoprussia       positive           308               13   0.073671
                 negative           308              231   1.309079
                 neutral            308               64   0.362688
putinwarcriminal neutral            295               48   0.272016
                 negative           295              234   1.326080
                 positive           295               13   0.073671
stopputin        positive           281               11   0.062337
                 neutral            281               44   0.249348
                 negative           281              226   1.280744
putin            positive           272               47   0.266349
                 neutral            272               93   0.527032
                 negative           272              132   0.748045
russian          positive           241                1   0.005667
                 negative           241              224   1.269409
                 neutral            241               16   0.090672

In [19]:
output = top_10_hashtags.reset_index().drop(columns='total_count')
output.to_csv(HASHTAG_OUTPUT_LOC)